# Site settings
title: Suyoung Lee
description: Suyoung Lee / 이수영. Postdoctoral researcher @KAIST WSP Lab.
url: https://leeswimming.com
# baseurl: "/particle" # the subpath of your site, e.g. /blog

timezone:          Asia/Seoul
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
  sass_dir: _sass

# User settings
username: Suyoung Lee
user_title: Security Researcher
user_description: >
  I am a postdoctoral researcher <a href="https://wsp-lab.github.io/" target="_blank">
  @KAIST WSP Lab</a>. My primary research interests lie at the intersection of
  artificial intelligence (AI) and computer security. In particular, I am
  interested in securing AI-based systems, web browsers, and web applications.
  I'm always happy to hear from you. For all inquiries, you can reach me at:
  <a href="mailto:suyoung.lee@kaist.ac.kr">suyoung.lee@kaist.ac.kr</a>
email: suyoung.lee@kaist.ac.kr
github: leeswimming
linkedin: suyoung-lee-669928152
google_scholar: whklEtMAAAAJ
# gplus_username:  lorem_ipsum
